### ISSUE TITLE
Slayer Eviscerate in ICB is counted as a seperate skill

### ISSUE THREAD

**Issue by Aistify** [lunyx/CasualMeter#10]
In sort by name its counted as one but if you sort by ID its separate from the vanilla Eviscerate.

**Comment by lunyx** [comment]
I don't think that's the case.  See here: http://i.imgur.com/AsE1Rmx.png

Red arrows indicate the start/end of ICB.  Yellow highlighted measured slice id's indicate they were not used during ICB and orange highlighted indicates that they were used during ICB.  You can match this up with the timing's on Ultimate OHS to confirm that this is the case.  Simply put, the game just has multiple skill id's for this skill for whatever reason, which is why I have the two different views in the first place.

**Comment by lunyx** [comment]
I've figured it out.  When measured slice is chained, it has a skill id of 230230, and when it isn't chained, it has a skill id of 230200.  I will be adding in a way to distinguish this, but it's not a result of ICB.
