### ISSUE TITLE
Not Connecting to Server

### ISSUE THREAD

**Issue by asuchis** [lunyx/CasualMeter#144]
Hello! I opened the meter before launching the game, and it doesn't connect to my server at all. I've tried relogging and reselecting servers, but it is not connecting to any server. I have everything I need to download, and I even see the tray when i open Tera, but it doesn't do anything. Please help.

**Comment by Gl0** [comment]
1. Install [npcap](https://nmap.org/npcap/)
2. run meter, game, check whether it's working
3. if not - 
3.1. uninstall npcap (not need, if not working on your system)
3.2. add firewall rule that allow all incoming traffic to meter .exe, you should specify full path to .exe, make sure that there is no macro in it like %AppData% (see https://github.com/neowutran/ShinraMeter/wiki/Window-firewall for screenshots)
3.3. in meter settings check "Use raw sockets instead of winpcap", close it.
3.4. run meter "as administrator", run game - should be working. If not - you've messed something with firewall rule.

3.2 should be done after each meter update (path changes).
