### ISSUE TITLE
Paste issue

### ISSUE THREAD

**Issue by wtfholdaggro** [lunyx/CasualMeter#27]
Hey,

I cannot paste DPS even with active chat window. But if I press ctrl+ins, tab out to Teamspeak (or whatever) and press ctrl+v it works fine but not in Tera. Its since the "Stepstone Island Update". 

Best regards,

Heiko

**Comment by lunyx** [comment]
Feel free to debug yourself, but many people including myself are unable to replicate this issue.  If you do figure out the underlying reason, I wouldn't mind fixing it or you can fix it and submit a pull request.

**Comment by Gl0** [comment]
Most likely problem is that tera is running with admin privileges and meter is not, so meter can't send anything to tera until you run meter itself as admin.

**Comment by lunyx** [comment]
I don't run as admin.

**Comment by Gl0** [comment]
I'm too, but game protection may force running it as admin (not sure, what protection is used on each region).

**Comment by lunyx** [comment]
As far as I know, there's nothing on NA.

**Comment by Gl0** [comment]
Anyway, one run as admin to check whether it helps is not so hard for issue starter.

**Comment by reloxx13** [comment]
Da fuk is, u cannot let it stay as "Run as Admin" on Win10. This is caused by the crap directory structure on Win10 (only???).

It gets Installed in AppData as "App". In their, their are multi folders for your application (mentioned before in another ticket) for every update. This means, the path to the exe is also changing after every update! Makes it senseless to create a shortcut for "Run as Admin".

HINT: Also i noticed, that the shortcut in the Startmenu of Win10 is a "Application Reference (.appref-ms)". You cannot check it to run as admin.

If you start by the exe, u wont get updates (did already mention it before in another ticket, too).
If u start by the entry in startmenu, u get updates but cannot start as admin and cannot paste dps.

Really, really annoying.

And if u r not running as admin, its wont paste dps, i think this has a secruity reason on some Windows versions (Win8 and above??).

@wtfholdaggro which is your Windows version?

**Comment by lunyx** [comment]
I've tested on both 8.1 and 10, and have no issues with pasting without running as admin.  Also, I'm already looking into changing the update thing.  You can blame Microsoft since that's their built-in implementation.

**Comment by Gl0** [comment]
Windows version is not the case. In any windows admin privileges required to interact with process, which is running with the same privileges. On RU client is running as regular user - so there is no need to run meter as admin, but some region is probably forcing client to be running as admin.
Gothos added runas manifest to his source a month ago to fix this issue.

**Comment by lunyx** [comment]
Just debunking the OS theory someone else brought up.  It would make sense if it's region based.  I just don't particularly like having it always run as an admin.  This should be remedied once I switch over to a different update mechanism, which should allow users to create a shortcut that will run it as admin.

**Comment by wtfholdaggro** [comment]
Hey all,

thanks for ur fast answers! I am running Win10 x64 Home Premium but, I got a solution for this issue. My Visual Studios is bugged on Win10, so a mate compiled the DPS Meter for me. Now I can run it as Admin without any problems.

**Comment by lunyx** [comment]
You can use the new download link on the main page.  This installation should allow you to set your shortcut to run as admin and continue to receive updates.
