### ISSUE TITLE
Please let me paste heal information.

### ISSUE THREAD

**Issue by Vysse** [lunyx/CasualMeter#34]
I would like to be able to paste Heal information. Like total heals and percentage of heals and total heal amount.

**Comment by lunyx** [comment]
I don't think this is relevant to a DPS meter.  Amount healed stats are pretty much useless since you can heal people while at max HP and it will still count.  This would lead to support classes prioritizing maximum heals while in fact buff/debuffs are more critical than keeping some clueless DPS alive.
