### ISSUE TITLE
Connecting server?

### ISSUE THREAD

**Issue by Shahrampain** [lunyx/CasualMeter#58]
i tryed many time to do every singel thing u said in guide but problem is it dont connect to any server at all , i run it as admin and tryed many time but it dont show i connect to server or not and not showing any dps at all

**Comment by mahoukoneko** [comment]
I have this going on too, not sure what I'm doing wrong. When I choose a character it doesn't change from how it looks when not connected. I even went back to the server select screen, which I don't usually do because it defaults to my server on startup, but choosing a server didn't ever make it say it was connected. Ahhh.

**Comment by Shahrampain** [comment]
yah same i tryed many time to select server, i even re inistalled my windows today from windows 7 to 10 to check how it work on new windows , i thought maybe it gonna work but it didnt >< some 1 help , how to make it work :<
